### ISSUE TITLE
Encoding a h256 video with a mp4 container failing

### ISSUE THREAD

**Issue by PHILLIPS71** [Unmanic/unmanic#225]
Have you read the [Code of Conduct](CODE_OF_CONDUCT.md)? By filing an Issue, you are expected
to comply with it, including treating everyone with respect:

Remember that these are some guidelines, use your best judgement.

### Description

I've just updated to the latest version and can no longer encode into H265 using libx265 with a MP4 container. Unsure if this is something I'm doing wrong on my end, looks like a lot has changed since the version I was previously running. I had no issues prior but now it cannot encode the video, audio seems to encode fine.

Plugins
- Video Encoder H265/HEVC - libx265 (CPU) v0.0.5
- Audio Encoder AC3 v0.0.1

I'm unsure if I need to append additional ffmpeg args to get this working, but I honestly have no idea what I'm doing in regards to ffmpeg which may well be what's wrong, but I'd assume when selecting the mp4 container it would add those on for me.

**Expected behavior:** 
To encode the video without erroring out

**Actual behaviour:**
Tests the file fine without issue but when it attempts to encode it fails instantly, I've attached the below logs

Command:
`ffmpeg -hide_banner -loglevel info -i /library/tvshows/Silicon Valley/Season 6/Silicon Valley - S06E05 - Tethics WEBDL-720p.mkv -strict -2 -max_muxing_queue_size 2048 -map 0:v:0 -map 0:a:0 -map 0:s:0 -c:v:0 libx265 -preset medium -crf 22 -c:a:0 copy -c:s:0 copy -y /tmp/unmanic/unmanic_file_conversion-1632728307.293362/Silicon Valley - S06E05 - Tethics WEBDL-720p-1632728307.293349-WORKING-1.mp4`

Logs:
```
Guessed Channel Layout for Input Stream #0.1 : 5.1

Input #0, matroska,webm, from '/library/tvshows/Silicon Valley/Season 6/Silicon Valley - S06E05 - Tethics WEBDL-720p.mkv':
 Metadata:
 encoder : libebml v1.3.9 + libmatroska v1.5.2
 creation_time : 2019-11-25T03:16:59.000000Z
 Duration: 00:32:03.93, start: 0.000000, bitrate: 4885 kb/s

 Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
 Metadata:
 BPS-eng : 4242937
 DURATION-eng : 00:32:03.922000000
 NUMBER_OF_FRAMES-eng: 46128
 NUMBER_OF_BYTES-eng: 1020385108
 _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
 _STATISTICS_WRITING_DATE_UTC-eng: 2019-11-25 03:16:59
 _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

 Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1, fltp (default)
 Metadata:
 title : English
 BPS-eng : 640000
 DURATION-eng : 00:32:03.904000000
 NUMBER_OF_FRAMES-eng: 60122
 NUMBER_OF_BYTES-eng: 153912320
 _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
 _STATISTICS_WRITING_DATE_UTC-eng: 2019-11-25 03:16:59
 _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
 
Stream #0:2(eng): Subtitle: subrip
 Metadata:
 title : English (SDH)
 BPS-eng : 106
 DURATION-eng : 00:32:02.250000000
 NUMBER_OF_FRAMES-eng: 758
 NUMBER_OF_BYTES-eng: 25497
 _STATISTICS_WRITING_APP-eng: mkvmerge v40.0.0 ('Old Town Road + Pony') 64-bit
 _STATISTICS_WRITING_DATE_UTC-eng: 2019-11-25 03:16:59
 _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

Stream mapping:
 Stream #0:0 -> #0:0 (h264 (native) -> hevc (libx265))
 Stream #0:1 -> #0:1 (copy)
 Stream #0:2 -> #0:2 (copy)

Press [q] to stop, [?] for help
x265 [info]: HEVC encoder version 3.2.1+1-b5c86a64bbbe
x265 [info]: build info [Linux][GCC 9.3.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
x265 [info]: Main profile, Level-3.1 (Main tier)
x265 [info]: Thread pool 0 using 24 threads on numa nodes 0,1
x265 [info]: Slices : 1
x265 [info]: frame threads / pool features : 4 / wpp(12 rows)
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
set_mempolicy: Operation not permitted
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge : hex / 57 / 2 / 3
x265 [info]: Keyframe min / max / scenecut / bias: 23 / 250 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb : 1 / 1 / 0
x265 [info]: References / ref-limit cu / depth : 3 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree : 2 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress : CRF-22.0 / 0.60
x265 [info]: tools: rd=3 psy-rd=2.00 early-skip rskip signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing lslices=4 deblock sao
[mp4 @ 0x5638016f9d40] track 1: codec frame size is not set
[mp4 @ 0x5638016f9d40] Could not find tag for codec subrip in stream #2, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument Error initializing output stream 0:0 -- encoded 0 frames 
Conversion failed!
```

**Reproduces how often:** 
100%

### Versions
Version - 0.1.1~108a5a6

### Installation Method Used
docker
