### ISSUE TITLE
Encoding using NVENC on Docker fails

### ISSUE THREAD

**Issue by fabicodes** [Unmanic/unmanic#228]
### Description
Encoding using NVENC via Docker fails every time while hardware transcoding via Plex (also running as docker-container) works just fine.

### Steps to Reproduce

1. Start to transcode using NVENC

**Expected behavior:** Transcoding should work correct

**Actual behaviour:** Transcoding fails
```
Stream mapping:
   Stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_nvenc))
   Stream #0:1 -> #0:1 (copy)
   Stream #0:2 -> #0:2 (copy)
   Stream #0:3 -> #0:3 (copy)
Press [q] to stop, [?] for help
[hevc_nvenc @ 0x560d1c298580] Cannot load libnvidia-encode.so.1
[hevc_nvenc @ 0x560d1c298580] The minimum required Nvidia driver for nvenc is 418.30 or newer
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

**Reproduces how often:** Every time

### Versions

- Unmanic Version - 0.1.1+68717c4
- NVIDIA Quadro P400
- Debian GNU/Linux 10 (buster)
- Linux 5.10.0-0.bpo.8-amd64
- Driver Version: 470.57.02
- CUDA Version: 11.4 
- Docker version 20.10.8, build 3967b7d
- nvidia-container-runtime/buster,now 3.5.0-1 amd64 [installed]

### Installation Method Used

Running using docker-compose, currently commented out the PUID/PGID for testing purposes, shouldn't make a difference as plex works with the same settings
```
  unmanic:
   image: josh5/unmanic:latest
   runtime: nvidia
   container_name: unmanic
   environment:
    #  - PUID=${PUID}
    #  - PGID=${PGID}
     - TZ=${TZ}
     - NVIDIA_DRIVER_CAPABILITIES=all
     - NVIDIA_VISIBLE_DEVICES=all
   volumes:
     - /docker/unmanic:/config
     - /storage/download/_extracted:/library
     - /tmp/unmanic:/tmp/unmanic
   ports:
     - 8887:8888
   restart: unless-stopped
```

### Additional Information

```
fabian:~/ $ cat /etc/nvidia-container-runtime/config.toml
disable-require = false
#swarm-resource = "DOCKER_RESOURCE_GPU"
accept-nvidia-visible-devices-envvar-when-unprivileged = true
#accept-nvidia-visible-devices-as-volume-mounts = false

[nvidia-container-cli]
#root = "/run/nvidia/driver"
#path = "/usr/bin/nvidia-container-cli"
environment = []
#debug = "/var/log/nvidia-container-toolkit.log"
#ldcache = "/etc/ld.so.cache"
load-kmods = true
#no-cgroups = false
#user = "root:video"
#ldconfig = "@/sbin/ldconfig"
ldconfig = "/sbin/ldconfig"
#ldconfig = "/sbin/ldconfig.real"

[nvidia-container-runtime]
#debug = "/var/log/nvidia-container-runtime.log"
```
```
fabian:~/ $ nvidia-smi
Thu Sep 30 12:56:46 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P400         Off  | 00000000:07:00.0 Off |                  N/A |
| 28%   43C    P0    N/A /  N/A |      0MiB /  2000MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
```
fabian:~/ $ docker exec -it unmanic nvidia-smi
Thu Sep 30 12:57:12 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P400         Off  | 00000000:07:00.0 Off |                  N/A |
| 28%   43C    P0    N/A /  N/A |      0MiB /  2000MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
```
fabian:~/ $ docker exec -it unmanic ldconfig -p | grep cuvid
        libnvcuvid.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
```

Hardware transcoding via plex works fine
```
  plex:
    container_name: plex
    restart: always
    runtime: nvidia
    image: ghcr.io/linuxserver/plex
    volumes:
      - /docker/plex:/config:rw
      - /tmp/plex_tmp:/transcode:rw
      - /storage/medien:/medien:rw
    network_mode: host
    environment:
      - TZ=${TZ}
      - HOSTNAME="PlexHost"
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=latest
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
```
