### ISSUE TITLE
There are no plugins

### ISSUE THREAD

**Issue by CalvoUTN** [Unmanic/unmanic#252]
### Description

I'm trying to install unmanic with Docker, but I don't think it's working how it should. I can't see any plugins installed, and I see the following:

- When I try to add a repository it says "New repository failed to save.".
- When I try to refresh repositories it says "Unable to update your configured repositories. Perhaps there is an error in one of the URLs?"

I can scan files by ticking scan on start and restarting the container, but nothing else happens, no workers or anything.
Also, Data panels is completely empty. 

This is my docker-compose:

```
version: '2.4'

services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    environment:
      - PUID=0
      - PGID=0
      - TZ=my-TZ
    volumes:
      - ./unmainc:/config
      - /mnt/olimpo/Series:/library
      - /mnt/olimpo/Cache:/tmp/unmanic
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
```

I'm using Ubuntu Server running on a VM on Proxmox. I'm currently hosting 40+ containers, including Jellyfin, Radarr, Sonarr, Nextcloud, etc.

### Steps to Reproduce

1. Copy my docker-compose.
2. Run ´sudo docker-compose up -d´
3. Go to localhost:8888 and see the app around.

**Expected behavior:** being able to see the installed plugins and other stuff in the docs.

**Actual behaviour:** as described.

### Versions

I tried the these tags for the image: latest, 0.1.3 and 0.1.2. All had problems.
The OS details are these:

´´´
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
´´´

### Installation Method Used

Docker and docker-compose.

### Additional Information

Pics of what I see

![imagen](https://user-images.githubusercontent.com/49721926/142568392-b9161c44-747e-491f-a368-8bc790585db1.png)
![imagen](https://user-images.githubusercontent.com/49721926/142568414-b5ff947b-1bbf-46cb-9f7a-4815779dfdbe.png)
![imagen](https://user-images.githubusercontent.com/49721926/142568460-357a0eb6-f1ac-4ab9-b80e-df1f217912f7.png)
![imagen](https://user-images.githubusercontent.com/49721926/142568490-a748fbd5-5ffc-4e78-80f6-eaf815c0804c.png)

Logs (I think there is something in the tornado file)
[UnmanicLogs.zip](https://github.com/Unmanic/unmanic/files/7567898/UnmanicLogs.zip)
