### ISSUE TITLE
Chmod changed on processed files

### ISSUE THREAD

**Issue by tetebueno** [Unmanic/unmanic#489]
### Description

When processing a file the resulting file has different permission flags the original. Maybe behaviour is exepected, but I couldn't find an issue or a plugin to tackle this.

### Steps to Reproduce

1. Add a file to process to the library with full permissions (`777`).
2. Wait for Unmanic to process the file.
3. Check the resulting file permissions.

**Expected behavior:** the processed file keeps the original file's permissions.

**Actual behaviour:** the processed file has different permissions (`644`), safer, yet different.

**Reproduces how often:** 100%

### Versions

Unmanic version: 0.2.6~41346cb

```console
$ docker exec -ti unmanic cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Installation Method Used

Running through Docker.

### Additional Information

Contents of the `docker-compose.yaml` file used to execute Unmanic:

```yaml
services:
  unmanic:
    image: josh5/unmanic
    container_name: unmanic
    restart: unless-stopped
    volumes:
      - /config:/config
      - /tmp/unmanic:/tmp/unmanic
      - /library:/library
    environment:
      - PUID=$USER_ID
      - PGID=$GROUP_ID
      - UMASK=002
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
```
