### ISSUE TITLE
No VAAPI device found

### ISSUE THREAD

**Issue by gabrielwhite** [Unmanic/unmanic#506]
### Description

I have installed the VAAPI plugin, and it's giving an error:

```
2024-10-16T12:56:26:ERROR:Unmanic.PluginExecutor - [FORMATTED] - Exception while carrying out 'worker.process_item' plugin runner 'encoder_video_hevc_vaapi'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/unmanic/libs/unplugins/executor.py", line 256, in execute_plugin_runner
    runner(data)
  File "/config/.unmanic/plugins/encoder_video_hevc_vaapi/plugin.py", line 374, in on_worker_process
    mapper.generate_default_vaapi_args()
  File "/config/.unmanic/plugins/encoder_video_hevc_vaapi/plugin.py", line 236, in generate_default_vaapi_args
    raise Exception("No VAAPI device found")
Exception: No VAAPI device found
```

The driver is available in the container:

```
ls -al /dev/dri
crw-rw---- 1 nobody render 226, 128 Oct 14 15:18 renderD128
```

The user abc is in the render group

```
cat /etc/group
render:x:106:abc
```

The user can succesfully access the driver

```
sudo -u abc vainfo
Trying display: wayland
error: XDG_RUNTIME_DIR not set in the environment.
Trying display: x11
error: can't connect to X server!
Trying display: drm
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_14
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: Mesa Gallium driver 23.2.1-1ubuntu3.1~22.04.2 for RENOIR (renoir, LLVM 15.0.7, DRM 3.57, 6.8.12-2-pve)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```

Here is my docker-compose.yaml

```
  services:
    unmanic:
      container_name: unmanic
      image: josh5/unmanic:latest
      ports:
        - 8181:8888
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
        - ./config:/config
        - /mnt/media/Series:/library/series
        - /mnt/media/Movies:/library/movies
        - /tmp/unmanic:/tmp/unmanic
        - ./customisation:/custom-cont-init.d:ro
      devices:
        - /dev/dri:/dev/dri
```

The custom-cont-init.d contains "groupfix.sh"

```
#!/bin/bash

groupadd --gid 106 render
usermod -aG render abc
```

### Versions

Ubuntu 22.04.5 LTS

### Installation Method Used

docker
