### ISSUE TITLE
Contained is using about 4% of CPU constnatly when idle

### ISSUE THREAD

**Issue by p4xel** [Unmanic/unmanic#510]
### Steps to Reproduce
I reinstalled docker container with default configuration. 
My docker-compose looks as follows:

```
---
services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
    - 9889:8888
    restart: unless-stopped
    environment:
    - PUID=1029
    - PGID=65537
    - TZ=Europe/London
    - LIBVA_DRIVER_NAME=i965
    volumes:
    - /volume1/docker/unmanic/config:/config
    - /volume1/docker/unmanic/tmp:/tmp/unmanic
    - /volume1/tv:/library/tv
    - /volume1/movie:/library/movie
    devices:
    - /dev/dri/renderD128:/dev/dri/renderD128       # For H/W transcoding using the VAAPI encoder
    - /dev/dri/card0:/dev/dri/card0
    healthcheck:
      disable: true
    networks:
      custom_net:
        ipv4_address: 172.18.36.10
    
networks:
  custom_net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.36.0/24
        gateway: 172.18.36.1
```

**Expected behavior:** Idle CPU usage <1%

### Versions

Latest docker image - Version: 0.2.8+925008e+dirty
OS: Synology DSM 7.2.2-72806 Update 1

### Installation Method Used

Docker on Synology DS920+ (Celeron J4125, RAM: 20GB)

Plugins configured:

- Convert any ASS subtitle streams in videos to SRT
- File Size Metrics Data Panel
- Ignore completed tasks
- Path Ignore
- Re-order audio streams by language
- Remove audio/subtitle streams by language
- Strip all image streams from file
- Video Encoder H265/HEVC - hevc_qsv (Intel)

### Additional Information

Executed ps aux within docker and got following output

```
root@b1708ff9c784:/# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0    432   104 ?        Ss   09:37   0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
root        17  0.0  0.0    208    80 ?        S    09:37   0:00 s6-supervise s6-linux-init-shutdownd
root        25  0.0  0.0    196     4 ?        Ss   09:37   0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdown
root        37  0.0  0.0    208    72 ?        S    09:37   0:00 s6-supervise s6rc-oneshot-runner
root        38  0.0  0.0    208    68 ?        S    09:37   0:00 s6-supervise s6rc-fdholder
root        39  0.0  0.0    208    76 ?        S    09:37   0:00 s6-supervise svc-cron
root        47  0.0  0.0    200    64 ?        Ss   09:37   0:00 /package/admin/s6/command/s6-ipcserverd -1 -- /package/admi
root       155  0.0  0.0   7364  3664 ?        Ss   09:37   0:00 bash ./run svc-cron
root       176  0.0  0.0   5764  1004 ?        S    09:37   0:00 sleep infinity
root       177  0.0  0.0    208    76 ?        S    09:37   0:00 s6-supervise unmanic
abc        179  3.9  0.2 1086980 47940 ?       Ssl  09:37   0:19 /usr/bin/python3 /usr/local/bin/unmanic-service
root       237  0.0  0.0   7628  4388 pts/0    Ss   09:45   0:00 /bin/bash
root       248  0.0  0.0  10064  1572 pts/0    R+   09:46   0:00 ps aux
```

I tried to disable everything, including file monitoring for library, but the issue still persists.
